### ISSUE TITLE
mingw32-make

### ISSUE THREAD

**Issue by Ptomaine** [lhmouse/MCF#9]
Hello lhmouse :)

Could you also include mingw32-make into your GCC-MCF distribution, please?

Thanks,
Arlen.

**Comment by lhmouse** [comment]
It used to be included, but was eventually removed, because few people are familiar with mixing Unix makefile syntax with CMD syntax and it is less likely to be useful.

If it is really necessary for you, you can get one from here <http://repo.msys2.org/mingw/x86_64/>, where it is called _mingw-w64-x86_64-make_ .

**Comment by lhmouse** [comment]
The primary reason why it was removed was that, it **did** frequently happen that quite a few people mistook `mingw32-make` for `make` and thought they could make use of a Unix makefile in CMD, which was not the case because the syntax of a Unix shell e.g. DASH is very different from that used by CMD. I haven't heard of much support for mingw32-make, except for CMAKE.

**Comment by Xeverous** [comment]
I would say that you should not remove something just because some people misuse it (C++ has many features easy to misuse but they exist and are introduced anyway).

> I haven't heard of much support for mingw32-make, except for CMAKE.

Many IDEs which work with any MinGW (Eclipse, Qt Creator, Code::Blocks, Visual Studio Code, KDevelop) expect it to contain `gcc`, `g++` and `make` or `mingw32-make` executables. CMake also expects it to be there. Yes, I can download a standalone Windows-GNU-make - it solves the problem but complicates CMake setup (`make` in a different directory than expected).

**Comment by lhmouse** [comment]
If **many** people misuse something, or seldom do people use it, then it probably shouldn't have existed.

But anyway, I will add it back in the next package, but it will be solely provided as a complement for CMake, just like what boost is for libstdc++.

**Comment by Ptomaine** [comment]
Thank you! :)
The single mingw32-make.exe file in the /bin folder would be enough ;)

**Comment by Xeverous** [comment]
Ahh, boost. You help people save so much time by providing ready to use boost. Really big thanks for this. And all the other libraries (z, OpenSSL, ncurses, ssp, SQLite, ...).

**Comment by lhmouse** [comment]
@Ptomaine Yes that is where it used to be.

@Xeverous Those are vanilla MSYS2 packages. A number of them have already been linked against **winpthreads** so malfunctions are expected. Header-only components are probably not subject to this issue.

**Comment by Xeverous** [comment]
What kind of malfunctions? Are the compiled libraries broken?

**Comment by lhmouse** [comment]
在 2019/7/29 19:19, Xeverous 写道:
> What kind of malfunctions? Are the compiled libraries broken?
> 
> —
>

Yes. It was reported that program that used `boost::thread` would crash.
Rebuilding boost will fix it apparently but I am not very willing to do
it because it is so time-consuming. boost uses a magical program named
`b2` which refuses to parallel compile; it takes 2x time to build boost
itself than everything else.


-- 
Best regards,
LH_Mouse

**Comment by Xeverous** [comment]
Which compiled libraries are broken? There should be a list of these ... or just they should just not exist in the build.

**Comment by lhmouse** [comment]
Chasing down broken libraries requires running a number of test programs with moderate coverage... that is not something I have at hand; and even I had, I would not bother myself rebuilding them. The entire building and packing process is not very automatic due to intermittent rejected patches which have to be fixed by hand.

**Comment by Xeverous** [comment]
It should be relatively simple to check which library is linked against winpthreads, although this is surprising (no `winpthreads`):

```
$ ldd libboost_thread-mt.dll
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffbb2790000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffbb2070000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffbaf4e0000)
        apphelp.dll => /c/Windows/SYSTEM32/apphelp.dll (0x7ffbace20000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7ffbb26c0000)
        libgcc_s_seh-1.dll => /c/mingw64/mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
        mcfgthread-12.dll => /c/mingw64/mingw64/bin/mcfgthread-12.dll (0x6c080000)
        libstdc++-6.dll => /c/mingw64/mingw64/bin/libstdc++-6.dll (0x6fc40000)
```

**Comment by lhmouse** [comment]
在 2019/7/31 上午4:16, Xeverous 写道:
> It should be relatively simple to check which library is linked against
> winpthreads, although this is surprising (no |winpthreads|):
> 
> |$ ldd libboost_thread-mt.dll ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll
> (0x7ffbb2790000) KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL
> (0x7ffbb2070000) KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll
> (0x7ffbaf4e0000) apphelp.dll => /c/Windows/SYSTEM32/apphelp.dll
> (0x7ffbace20000) msvcrt.dll => /c/Windows/System32/msvcrt.dll
> (0x7ffbb26c0000) libgcc_s_seh-1.dll =>
> /c/mingw64/mingw64/bin/libgcc_s_seh-1.dll (0x61440000) mcfgthread-12.dll
> => /c/mingw64/mingw64/bin/mcfgthread-12.dll (0x6c080000) libstdc++-6.dll
> => /c/mingw64/mingw64/bin/libstdc++-6.dll (0x6fc40000) |
> 
> 

There was probably something linked statically (inline functions and
function template specializations for example, as well as class members,
which might take up a different number of bytes). Mutexes and condition
variables in mcfgthread only take a pointer size, so it is unlikely to
cause overflows. The statically initializers, referenced in libstdc++
from winpthreads and mcfgthread, are different too (the former being
`PTHREAD_MUTEX_INITIALIZER` which is a negative `intptr_t`, while the
latter being zero).


-- 
Best regards,
LH_Mouse

**Comment by Xeverous** [comment]
Ok, any idea how to solve this problem then? I had some executables crashing at startup and maybe this was the issue? I'm not sure what to do but now using your compiler builds is a bit risky if I don't even know what library is safe to use.

**Comment by lhmouse** [comment]
1. Programs that are linked against only standard CRT (it's MSVCRT at the moment, since I don't enable UCRT) and Windows libraries (KERNEL32, SHELL32, USER32, etc.) should not suffer from this.
2. C libraries (Python, OpenSSL) etc. that do not play with GCC internal stuff should be okay too.
3. C++ libraries that are header-only are safe apparently (most of boost).
4. Other libraries that references `std::thread`, `std::mutex`, `std::once_flag`, `std::condition_variable` from libstdc++ may be out of luck. In order to work appropriately, they have to be rebuilt.
